**What is an Array?**

An array is a special variable, which can hold more than one value at a time.



*   Python does not have ** built-in** support for Arrays, but Python Lists can be used instead.

*   How to use LISTS as ARRAYS, however, to work with arrays in Python you will have to import a library, like the NumPy library.



In [1]:
import array

# or you can also use

from array import *  

## List

In [10]:
Color = ["Red", "Green", "Blue"]
Color

['Red', 'Green', 'Blue']

In [34]:
# Indexing in List

print(Color[1])  # positive indexing

print("\n---- \t ---- \n")
print(Color[-1]) # negative 

print("\n---- \t ---- \n")
print(Color[0:3]) #Positive Slicing

print("\n---- \t ---- \n")
print(Color[-3:-1]) #Negative slicing


Green

---- 	 ---- 

Blue

---- 	 ---- 

['Red', 'Green', 'Blue']

---- 	 ---- 

['Red', 'Green']


## **Looping in Array Elements**

In [36]:
name = ['Ali','Abdullah','Omer','Hamza','Talha']
name

['Ali', 'Abdullah', 'Omer', 'Hamza', 'Talha']

In [39]:
# Simple for loop
for y in name:
  print(y)

Ali
Abdullah
Omer
Hamza
Talha


In [50]:
# Nested loop
for l in name:
  if l == name[3]:
    break
  else:
    print(l)

Ali
Abdullah
Omer


### **Removing Array Elements**

In [63]:
# pop() removes the specific valaue by using the index
name = ['Ali','Abdullah','Omer','Hamza','Talha']
name.pop(2)
print(name)

['Ali', 'Abdullah', 'Hamza', 'Talha']


In [64]:
# To check list method use
dir(list)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

## Array Methods

In [65]:
# In order to check the array method use this
dir(array)

['__add__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'buffer_info',
 'byteswap',
 'count',
 'extend',
 'frombytes',
 'fromfile',
 'fromlist',
 'fromstring',
 'fromunicode',
 'index',
 'insert',
 'itemsize',
 'pop',
 'remove',
 'reverse',
 'tobytes',
 'tofile',
 'tolist',
 'tostring',
 'tounicode',
 'typecode']

## Array 

Array itself create a single dimensional array

In order to create a multi-dimensional array we use numpy
    

**Array:**

1.   Can only Create a Single dimensional array
2.   Slow 
3.   Use the high memory


**Numpy:**

1.   Can Create a multi-dimensional array
2.   Faster 
3.   Use the low memory



In [67]:
import array
from array import *

In [70]:
# Syntax: variable_name = array("datatype",[array])
# it is a single dimensional array
arr = array("i",[1,2,3,4,5])
arr

array('i', [1, 2, 3, 4, 5])

In [78]:
# if you try to create a multi-dimensional array it will give you an erro
# arr = array("i",[1,2,3],[4,5,6])
#  TypeError: array() takes at most 2 arguments (3 given)
# this error telling us that we can create only single dimensional array by using the array module

In [79]:
import numpy as np
from numpy import *

# it will allow you

In [96]:
arra = np.array([
                 [1,2,3,4],
                 [5,6,7,8]
                 ])
arra

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [104]:
# To check the shape of the array
arra.shape

(2, 4)

In [111]:
# it will inform you, how much memory can store it 
arra.itemsize

arra.size

8

In [107]:
# check the datatype of the array
arra.dtype

dtype('int64')

In [120]:
# Check the dimension of the array
arra.ndim

2

In [123]:
# Check the diagnoal of the array
arra.diagonal()

array([1, 6])

In [113]:
ar = np.array([
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]
                 ])
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [127]:
# ar.shape
# ar.ndim
# ar.dtype
# ar.diagonal()

# **Sunnary and Statistics**

In [130]:
ar.sum()

78

In [132]:
ar.mean()

6.5

In [134]:
ar.std()

3.452052529534663

In [136]:
ar.var()

11.916666666666666

In [138]:
# inorder to get the value accordingly axies

In [143]:
# axis= 0 represents the Colums
ar.sum(axis=0)

array([15, 18, 21, 24])

In [145]:
# axis= 1 represents the rows
ar.sum(axis=1)

array([10, 26, 42])

In [149]:
ar.mean(axis=0)  #Colums

array([5., 6., 7., 8.])

In [150]:
ar.mean(axis=1) #rows

array([ 2.5,  6.5, 10.5])

In [151]:
ar.std(axis=0) #colums

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [154]:
ar.std(axis=1) #rows

array([1.11803399, 1.11803399, 1.11803399])

In [158]:
a = sin(ar)
a

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [160]:
a = cos(ar)
a

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362],
       [ 0.28366219,  0.96017029,  0.75390225, -0.14550003],
       [-0.91113026, -0.83907153,  0.0044257 ,  0.84385396]])

In [163]:
a = tan(ar)
a

array([[ 1.55740772e+00, -2.18503986e+00, -1.42546543e-01,
         1.15782128e+00],
       [-3.38051501e+00, -2.91006191e-01,  8.71447983e-01,
        -6.79971146e+00],
       [-4.52315659e-01,  6.48360827e-01, -2.25950846e+02,
        -6.35859929e-01]])

In [166]:
ar.min()

1

In [167]:
ar.max()

12

## Boolean Array

In [171]:
my_arr = np.array([9,10,11,12])
my_arr

array([ 9, 10, 11, 12])

In [173]:
# in order to get value by using the boolean
my_arr[[True,False,False,True]]

array([ 9, 12])

## Linear Algebra

In [186]:
ar1= np.array([
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]
                 ])
ar1.reshape(4,3)


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [187]:
ar2 = np.array([
                 [1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]
                 ])
ar2.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Size of Objects in Memory

# Int and Float

In [191]:
import sys
sys.getsizeof(1)

28

In [197]:
sys.getsizeof(1000*1888)

28

## Numpy size is much smaller

In [199]:
np.dtype(int).itemsize

8

In [201]:
np.dtype(float).itemsize

8

In [203]:
np.dtype(str).itemsize

0

## Lists are even larger

In [205]:
sys.getsizeof([1])

80

In [208]:
sys.getsizeof([1,2,3]) #Further increase

96

## Performance in array and numpy which is very important

In [215]:
# In list the speed
l = list(range(100))
% time sum([x**2 for x in l])

CPU times: user 118 µs, sys: 11 µs, total: 129 µs
Wall time: 135 µs


328350

In [217]:
l = list(range(1000000))
% time sum([x**2 for x in l])

CPU times: user 392 ms, sys: 27.8 ms, total: 420 ms
Wall time: 418 ms


333332833333500000

In [213]:
# In array the speed
a  = np.arange(1000)
% time sum(a**2)

CPU times: user 243 µs, sys: 0 ns, total: 243 µs
Wall time: 254 µs


332833500

In [218]:
a  = np.arange(1000000)
% time sum(a**2)

CPU times: user 4.29 ms, sys: 14 µs, total: 4.3 ms
Wall time: 4.76 ms


333332833333500000

## Usefull numpy funcions

In [220]:
# random()
# arrange()
# reshape()
# linespae()
# logspace()
# zeros()
# ones()
# empty()
# identity()
# eye()